; ===================================== ;
;   H U D   A D V E R T I S E M E N T   ;
; ===================================== ;

VIP AVAILABLE - DON'T MISS THE ADVANTAGE

SUPPORT THE SERVER TO KEEP IT ONLINE

RESET YOUR SCORE ANYTIME - TYPE /RS

NEED HELP WITH COMMANDS? ASK ADMIN IN CHAT

UNLOCK PREMIUM FEATURES - TYPE /VIP

TRACK YOUR PROGRESS - TYPE /RANK

CHANGE CAMERA MODE - TRY /CAM IN-GAME
